use clap::{App, Arg, ArgMatches, AppSettings, SubCommand};

pub fn get_matches<'a>(default_config_path: &'a str) -> ArgMatches<'a> {
    let app = App::new("repo-rs")
        .about("Manage multiple git repositories")
        .author(crate_authors!())
        .version(crate_version!())
        .global_setting(AppSettings::ColorAuto)
        .global_setting(AppSettings::ColoredHelp)
        .arg(Arg::with_name("config")
                 .help("sets the config file to use")
                 .takes_value(true)
                 .default_value(default_config_path)
                 .short("c")
                 .long("config")
                 .global(true))
        .subcommand(SubCommand::with_name("list").about("lists tracked repos"))
        .subcommand(SubCommand::with_name("status").about("gets status for tracked repos"))
        .subcommand(SubCommand::with_name("track")
                        .about("track an existing repo")
                        .arg(Arg::with_name("path")
                                 .help("the path of the repository to track")
                                 .index(1)
                                 .default_value(".")
                                 .required(false))
                        .arg(Arg::with_name("key")
                                 .help("A unique identifier for the tracked repo (defaults to directory name)")
                                 .takes_value(true)
                                 .short("k")
                                 .long("key"))
                        .arg(Arg::with_name("branch")
                                 .help("The branch to track")
                                 .takes_value(true)
                                 .default_value("master")
                                 .short("b")
                                 .long("branch")))
        .subcommand(SubCommand::with_name("untrack").about("stop tracking a repo"))
        .subcommand(SubCommand::with_name("clone").about("clone a repo and start tracking it"))
        .subcommand(SubCommand::with_name("prune").about("prune merged/deleted branches"))
        .subcommand(SubCommand::with_name("pull")
                        .about("pull all tracked repos")
                        .arg(Arg::with_name("stash")
                                 .help("stash any uncommitted changes prior to the merge")
                                 .short("s")
                                 .long("stash")));
    app.get_matches()
}
